### ISSUE TITLE
[FR] Paragraph space.

### ISSUE THREAD

**Issue by barmallion** [ingrammicro/puzzle-tokens#13]
![image](https://user-images.githubusercontent.com/17190030/69334337-8627a300-0c6b-11ea-896e-f7c346592231.png)

**Comment by MaxBazarov** [comment]
Added "pt-paragraph-spacing" style property to setup Paragraph Spacing
Example: https://github.com/ingrammicro/puzzle-tokens/tree/master/Styles/Releases/6.12.0
