### ISSUE TITLE
[FR] Multiple Box-Shadow Properties

### ISSUE THREAD

**Issue by tamcao** [ingrammicro/puzzle-tokens#20]
Trying to get multiple shadows properties to work but it doesn't seem to work.

For example:
background: rgba(255,255,255,0.00);
box-shadow: 0 7px 40px 0 rgba(0,0,0,0.13), 0 2px 8px 0 rgba(0,0,0,0.24);
border-radius: 4px;

Is this currently supported in the plugin?
![57F06D2D-FE96-48E7-ABDE-F4F8B43B38BD](https://user-images.githubusercontent.com/4138046/71497758-ad076500-2827-11ea-959e-9418d5861c31.png)

**Comment by MaxBazarov** [comment]
Unfortunately multiple shadows  are not supported rigth now.
But probably it's not too hard to support. Stay tunned.

**Comment by MaxBazarov** [comment]
Supported in 6.7.0 updated!
