### ISSUE TITLE
Plugin not working on cloud documents

### ISSUE THREAD

**Issue by tijmenvangurp** [ingrammicro/puzzle-tokens#22]
```
ENOENT: no such file or directory, open '/Users/my-user-name/Library/Application%20Support/com.bohemiancoding.sketch3/CloudDocuments/813d2e60-b534-4276-8d04-20a31f48bb7f/puzle-tokens-text-and-layer-styles-vars.scss'
```

I am not 100% what goes wrong here? But it seems the in-between JSON/CSS file is not saved correctly. 

A workaround, for now, is to make it a local document and then save it to the cloud manually. But ideally would like to see this fixed. 

Thanks for the great plugin 👍  let me know if you need additional details.

**Comment by MaxBazarov** [comment]
Hello, Sure. It should be fixed.  Also you can disable “Generate symbols…” checkbox in Configuration.

**Comment by MaxBazarov** [comment]
I have tried to improve diagnostic for this case in the latest  8.3.0 release

**Comment by MaxBazarov** [comment]
If you don't need to integrate PT with Puzzle Publisher — just don't enable "Generate symbols…" checkbox.

But if you need then we need to find some solution — where store an information about styles and symbols.

Anyway, I need to disabled symbol/style file generation for Cloud libraries.

**Comment by MaxBazarov** [comment]
Fixed.
