### ISSUE TITLE
Special character in classname

### ISSUE THREAD

**Issue by tijmenvangurp** [ingrammicro/puzzle-tokens#23]
Probably a bit an edge case, but maybe easy to fix?

I want to use the character `Ω` in the class/layer style name.
This because it is later in the alphabet, and thus later in the list.

I always get the error
```
Failed to parse SASS with error message:

Cannot read property 'props' of null
```
I guess it is not an allowed classname in css. would it be possible to fix it e.g. with the `--PT-` prefix? 

If not also fine, then I know I need to go for another solution.

![image](https://user-images.githubusercontent.com/9990026/79365139-842bec80-7f4a-11ea-9822-7373bf01267c.png)

**Comment by MaxBazarov** [comment]
Yep. I can bring some workaround. Let me think about.

**Comment by MaxBazarov** [comment]
With PT 8.3.2 you can add @charset "UTF-8"; as the first line to your file and use any UTF8 characters.  See the example below.

```
@charset "UTF-8";
.Ωcolour {
    color:              red;
}
```
