### ISSUE TITLE
Improve error message on block comments in scss

### ISSUE THREAD

**Issue by tijmenvangurp** [ingrammicro/puzzle-tokens#24]
using `*/block comments/*` in scss gives the following error message:

![image](https://user-images.githubusercontent.com/9990026/79568955-0c2f0500-80b7-11ea-9b0f-a5469908546e.png)

It seems that these types of comments are not allowed. would be nice if there is a more helpful error message.

**Comment by MaxBazarov** [comment]
/* comment */ should work fine.
Could you share the SCSS example?

**Comment by tijmenvangurp** [comment]
doesn't matter what scss
```scss
/*comment*/
.test {
  color: red;
}
```
e.g. above code results in the described error

`node v10.16.0`
`sass@1.26.3`

**Comment by MaxBazarov** [comment]
Yep. It’s my fault. I parse single line comment in a wrong way.  Will fix it asap.
For now you can replace 
/*comment*/
by
/*comment
*/
To get it working.

**Comment by tijmenvangurp** [comment]
No biggy took me a while to figure out why my scss was not working want to prevent that others have the same experience :)

**Comment by MaxBazarov** [comment]
Fixed in 8.3.0
