### ISSUE TITLE
mix-blend-mode

### ISSUE THREAD

**Issue by asknback** [ingrammicro/puzzle-tokens#34]
Hi, would it be possible to use ["mix-blend-mode"](https://www.w3schools.com/cssref/pr_mix-blend-mode.asp) in this plugin in some way? If so, how?

**Comment by MaxBazarov** [comment]
Could you send me an example of Sketch file with proposed result?

**Comment by asknback** [comment]
Hey, thanks for looking into it. I added both a screenshot and a file where a layer uses a blend mode.

Cheers.

![Screenshot 2020-10-23 at 11 47 09](https://user-images.githubusercontent.com/4488710/96989287-c51e4280-1525-11eb-81a7-2f1d9bb06955.png)


[Blend-Mode-Test.zip](https://github.com/ingrammicro/puzzle-tokens/files/5428711/Blend-Mode-Test.zip)

**Comment by asknback** [comment]
Also the Sass snippet for the above would be something like:

`Controls {
	.Overlay {
		mix-blend-mode: lighten;
		background-color: #FF03F8;	
	}
}`

**Comment by MaxBazarov** [comment]
I think it’s possible to support mix-blend-mode.
Will implement it on Monday. 


> 23 Oct 2020, в 12:53, Magnus Askenbäck <notifications@github.com> написал(а):
> 
> Controls { .Overlay { mix-blend-mode: lighten; background-color: #FF03F8; } }
> 
>

**Comment by asknback** [comment]
That’s awesome. 💪

**Comment by MaxBazarov** [comment]
Implemented in 8.13.0!
mix-blend-mode:         normal; // normal / darken / multiply / color-burn / lighten / screen / color-dodge / overlay / difference 
                                    // exclusion / hue / saturation / color / luminosity

**Comment by asknback** [comment]
Awesome. I will update our SASS accordingly.
Cheers buddy!

Magnus

**Comment by MaxBazarov** [comment]
Great!

**Comment by asknback** [comment]
Another question. Would it be possible to update the new "color variables"
with Puzzle tokens as well?
https://www.sketch.com/docs/styling/#color-variables

Best,
Magnus

**Comment by asknback** [comment]
My programming skills are sub-par, but found this post in the plugin forum
- https://sketchplugins.com/d/2190-update-a-color-variable-via-api

**Comment by MaxBazarov** [comment]
Unfortunately Sketch did not provide JS API to manage color variables. I’m still waiting for their response. Will keep you in touch.

**Comment by MaxBazarov** [comment]
Oops. I was wrong.  API exists.  
I’m going to support it.

**Comment by asknback** [comment]
That’s great news. Looking forward to try it out!  💥

**Comment by MaxBazarov** [comment]
@asknback 
https://spectrum.chat/puzzle-tokens/general/8-14-1-released~a8ae752a-36c5-438e-9ac3-47245d398401
