### ISSUE TITLE
[Request] Link color variable into the layer/text style

### ISSUE THREAD

**Issue by tgt95** [ingrammicro/puzzle-tokens#36]
Your plugin is very useful! 
Can I link the color variable to the layer style or text style? I want those styles will link with the color variable.

**Comment by MaxBazarov** [comment]
The idea is reach.
Could you imagine how It can look in LESS/SASS?

**Comment by tgt95** [comment]
In my idea, do we have Sketch properties about Color Variables? It's will attach to the code. Example:

.--COLORS-{
	.Transparent{
		// This will create a Color variable has a name is [Transparent]
		background-color: rgba(black, 0);
	}
}

.Transparent{
	// This will create a Layer style has a name is [Transparent]
	background-color: rgba(black, 0);
	// In my imagine
	--sketch-inherit-color-prop: 'Transparent';
}

Just an idea, If it doesn't work like that, please ignore this.

**Comment by MaxBazarov** [comment]
Ok. I understand the idea. 
Let me investigate it deeply.

**Comment by tgt95** [comment]
Thanks for your answer! 👍

**Comment by MaxBazarov** [comment]
Fixed in 8.15.0
See the following example:

.--COLORS-{
	.Transparent{
		color:  black;
	}
}

.Transparent{
	background-color: "Transparent";

}
