### ISSUE TITLE
Some way to rename loaded file Untitled.less -> given_name.less

### ISSUE THREAD

**Issue by ZvezdocheTag** [ingrammicro/puzzle-tokens#37]
Hey, thanks for the plugin. 

There is some way to define name of the .less or .sass file that are exported with help of `puzzle-tokens`?

**Comment by MaxBazarov** [comment]
Currently it uses the name of Sketch document as a name for less/scss file.

I can add option to change it. It’s easy.

**Comment by ZvezdocheTag** [comment]
Got it, thanks.

Yeah, I think it can be helpful.

In my use case, I will receive this tokens file from designer, and easier to configure it's one time inside plugin, and then maintain  the same file inside the code, without manual renaming .

**Comment by MaxBazarov** [comment]
Agree. Is it ok to save a name per a Sketch file? Or do you need to get the same common name for any Sketch files?

**Comment by ZvezdocheTag** [comment]
I think about common name for any Sketch files. 

Like if we will have setup designer -> developer workflow, and common high level code structure, should be more convenient to have one name for all. If we want to start new project, just use the same flow with the same structure and names.

something like this:
`./themes/puzzle-tokens.{.less, .scss}`

**Comment by MaxBazarov** [comment]
Changed in 8.15.0
Now PT always exports styles to /puzzle-tokens.{.less, .scss}

**Comment by ZvezdocheTag** [comment]
Thanks
