### ISSUE TITLE
Plugin is not Running anymore after Update

### ISSUE THREAD

**Issue by vkoopmans-resoluut** [ingrammicro/puzzle-tokens#45]
HI @MaxBazarov 

I get this error after updating, havent changed anything to my code, just updated sketch and your plugin?

<img width="744" alt="Screenshot 2021-09-30 at 15 09 44" src="https://user-images.githubusercontent.com/40267611/135461790-85bb4068-bd3c-4ad1-b507-1f107bf6752b.png">
?

**Comment by MaxBazarov** [comment]
Sorry, it’s my fault. 
Will fix it today

**Comment by MaxBazarov** [comment]
You can find the previous version in Archives

**Comment by vkoopmans-resoluut** [comment]
Thanks, will pick that one :)

**Comment by MaxBazarov** [comment]
@vkoopmans-resoluut  Please try 8.17.2 update.

**Comment by vkoopmans-resoluut** [comment]
🙏 perfect again!

**Comment by MaxBazarov** [comment]
> Yes that error is gone!
> Though I get an error on font-spacing "normal".
> It runs fine in 8.17.0,

font-spacing or letter-spacing?

I tried the following code and it works fine.

.test{
    color:              orange;
    letter-spacing:       20px;
}
