### ISSUE TITLE
[FR] Letter Spacing

### ISSUE THREAD

**Issue by mikebronner** [ingrammicro/puzzle-tokens#8]
Would love to see the `letterspacing` CSS property adopted. Let me know if there is any information I can provide to help with this. Thanks!

**Comment by tamcao** [comment]
First of all, thank you so much for this plugin as it made scaffolding styles so much quicker via code. I second that request for the letter-spacing property.  This one is especially important for us designers.

**Comment by MaxBazarov** [comment]
Added in 6.2.0
letter-spacing:        10px;      // <value>px, "normal"
